// Static vehicle data - matches the 18-vehicle fleet
// Used for production where Vercel cannot access local SQLite

export interface Vehicle {
  id: string;
  slug: string;
  make: string;
  model: string;
  year: number;
  category: string;
  bodyStyle: string;
  tagline: string;
  description: string;
  dailyRate: number;
  weekendRate?: number;
  weeklyRate?: number;
  securityDeposit: number;
  horsepower: number;
  engine: string;
  zeroToSixty: string;
  topSpeed: string;
  transmission: string;
  drivetrain: string;
  seats: number;
  doors: number;
  luggage: number;
  convertible: boolean;
  available: boolean;
  featured: boolean;
  premierVerified: boolean;
  instantConfirm: boolean;
  displayOrder: number;
  images: { url: string; alt: string; isMain: boolean; position?: string }[];
  badges: { name: string; label: string; icon: string }[];
}

export const vehicles: Vehicle[] = [
  { id: "1", slug: "mercedes-maybach-s680-virgil-abloh", make: "Mercedes-Maybach", model: "S680 by Virgil Abloh", year: 2024, category: "LUXURY", bodyStyle: "SEDAN", tagline: "The Virgil Abloh edition. Part art piece, part limousine.", description: "The most exclusive sedan ever offered. A collaboration between Mercedes-Maybach and the late Virgil Abloh. Only 150 units worldwide.", dailyRate: 2399, weekendRate: 2599, weeklyRate: 2199, securityDeposit: 4300, horsepower: 621, engine: "6.0L V12 Biturbo", zeroToSixty: "4.4s", topSpeed: "130 mph", transmission: "Automatic", drivetrain: "AWD", seats: 4, doors: 4, luggage: 3, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 1, images: [{ url: "https://www.jswluxurygroup.com/cars/maybach-virgil/web/maybach-virgil-1.jpg", alt: "Mercedes-Maybach S680 by Virgil Abloh", isMain: true }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "2", slug: "lamborghini-huracan-tecnica", make: "Lamborghini", model: "Huracán Tecnica", year: 2024, category: "EXOTIC", bodyStyle: "COUPE", tagline: "Rear-drive, razor sharp.", description: "The driver's Huracán. Built for those who want to feel every corner. Naturally aspirated V10 with rear-wheel drive.", dailyRate: 1599, weekendRate: 1799, weeklyRate: 1499, securityDeposit: 2590, horsepower: 631, engine: "5.2L V10", zeroToSixty: "3.2s", topSpeed: "202 mph", transmission: "Dual-Clutch", drivetrain: "RWD", seats: 2, doors: 2, luggage: 1, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 2, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785365256453-fb78ml.png", alt: "Lamborghini Huracán Tecnica", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785367230896-f28gs3.png", alt: "Lamborghini Huracán Tecnica", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785367247552-tadrok.jpg", alt: "Lamborghini Huracán Tecnica", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785365248881-7dw21x.png", alt: "Lamborghini Huracán Tecnica", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "3", slug: "lamborghini-huracan-evo-spyder", make: "Lamborghini", model: "Huracán EVO Spyder", year: 2024, category: "EXOTIC", bodyStyle: "CONVERTIBLE", tagline: "Same V10 fury. Open sky.", description: "The Spyder turns every Montreal drive into a cinematic experience. Naturally aspirated V10 with all-wheel drive.", dailyRate: 1499, weekendRate: 1699, weeklyRate: 1399, securityDeposit: 2390, horsepower: 631, engine: "5.2L V10", zeroToSixty: "3.1s", topSpeed: "202 mph", transmission: "Dual-Clutch", drivetrain: "AWD", seats: 2, doors: 2, luggage: 1, convertible: true, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 3, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785367322647-2fq7e3.png", alt: "Lamborghini Huracán EVO Spyder", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785367413563-q6gaxo.png", alt: "Lamborghini Huracán EVO Spyder", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785367418838-3ckd2z.png", alt: "Lamborghini Huracán EVO Spyder", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "4", slug: "lamborghini-urus-performante", make: "Lamborghini", model: "Urus Performante", year: 2024, category: "EXOTIC", bodyStyle: "SUV", tagline: "The Urus on steroids.", description: "Lower, louder, faster. Performante means business and Montreal feels it. The ultimate Super SUV.", dailyRate: 1399, weekendRate: 1599, weeklyRate: 1299, securityDeposit: 2390, horsepower: 657, engine: "4.0L V8 Biturbo", zeroToSixty: "3.3s", topSpeed: "190 mph", transmission: "Automatic", drivetrain: "AWD", seats: 5, doors: 4, luggage: 4, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 4, images: [{ url: "https://www.jswluxurygroup.com/cars/lamborghini-urus-performante/web/24p06299.jpg", alt: "Lamborghini Urus Performante", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/lamborghini-urus-performante/web/24p06316.jpg", alt: "Lamborghini Urus Performante", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/lamborghini-urus-performante/web/24p06313.jpg", alt: "Lamborghini Urus Performante", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "5", slug: "lamborghini-huracan-evo", make: "Lamborghini", model: "Huracán EVO", year: 2024, category: "EXOTIC", bodyStyle: "COUPE", tagline: "The naturally aspirated V10 screams.", description: "Pure Lambo energy through the streets of Downtown Montreal. All-wheel drive confidence with rear-wheel drive soul.", dailyRate: 1499, weekendRate: 1699, weeklyRate: 1399, securityDeposit: 2190, horsepower: 610, engine: "5.2L V10", zeroToSixty: "3.3s", topSpeed: "202 mph", transmission: "Dual-Clutch", drivetrain: "AWD", seats: 2, doors: 2, luggage: 1, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 5, images: [{ url: "https://www.jswluxurygroup.com/cars/lamborghini-huracan/web/huracan-1.jpg", alt: "Lamborghini Huracán EVO", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785418323684-h99zak.jpeg", alt: "Lamborghini Huracán EVO", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785418326420-z6mh7r.jpeg", alt: "Lamborghini Huracán EVO", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/lamborghini-huracan/web/huracan-4.jpg", alt: "Lamborghini Huracán EVO", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "6", slug: "mclaren-600lt-spider", make: "McLaren", model: "600LT Spider", year: 2024, category: "EXOTIC", bodyStyle: "CONVERTIBLE", tagline: "Longtail aggression meets open-air freedom.", description: "The 600LT is the sharpest tool in Montreal. Carbon fiber everything, twin-turbo V8, and a folding hardtop.", dailyRate: 1999, weekendRate: 2099, weeklyRate: 10099, securityDeposit: 10000, horsepower: 592, engine: "3.8L V8 Biturbo", zeroToSixty: "2.8s", topSpeed: "204 mph", transmission: "Dual-Clutch", drivetrain: "RWD", seats: 2, doors: 2, luggage: 1, convertible: true, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 6, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368311030-yvi84b.jpg", alt: "McLaren 600LT Spider", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368307678-pftyo9.jpg", alt: "McLaren 600LT Spider", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368315058-p0ri44.png", alt: "McLaren 600LT Spider", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368318781-njlvqt.jpg", alt: "McLaren 600LT Spider", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368321168-uznes3.jpg", alt: "McLaren 600LT Spider", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "7", slug: "mercedes-amg-g63-urban-kit", make: "Mercedes-AMG", model: "G63 Urban Kit", year: 2024, category: "LUXURY", bodyStyle: "SUV", tagline: "The G-Wagon, amplified.", description: "Urban Kit body kit turns Montreal's favorite SUV into a rolling statement. AMG power with iconic presence.", dailyRate: 1199, weekendRate: 1299, weeklyRate: 1099, securityDeposit: 1990, horsepower: 577, engine: "4.0L V8 Biturbo", zeroToSixty: "4.4s", topSpeed: "149 mph", transmission: "Automatic", drivetrain: "AWD", seats: 5, doors: 4, luggage: 4, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 7, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368403548-pjzlcd.jpg", alt: "Mercedes-AMG G63 Urban Kit", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368406270-tj0a9h.jpg", alt: "Mercedes-AMG G63 Urban Kit", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368408610-meeumj.jpg", alt: "Mercedes-AMG G63 Urban Kit", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "8", slug: "lamborghini-urus", make: "Lamborghini", model: "Urus", year: 2024, category: "EXOTIC", bodyStyle: "SUV", tagline: "The world's first Super SUV.", description: "641 horses of Italian fury built for Montreal's widest boulevards. The SUV that thinks it's a supercar.", dailyRate: 1399, weekendRate: 1499, weeklyRate: 1399, securityDeposit: 1790, horsepower: 641, engine: "4.0L V8 Biturbo", zeroToSixty: "3.6s", topSpeed: "190 mph", transmission: "Automatic", drivetrain: "AWD", seats: 5, doors: 4, luggage: 4, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 8, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368530781-59hwca.jpg", alt: "Lamborghini Urus", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368534931-cgbkvb.jpg", alt: "Lamborghini Urus", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368537473-m5ec9h.jpg", alt: "Lamborghini Urus", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "9", slug: "mercedes-maybach-gls-600", make: "Mercedes-Maybach", model: "GLS 600", year: 2024, category: "LUXURY", bodyStyle: "SUV", tagline: "The ultimate luxury SUV.", description: "Rear executive seats, ambient lighting, and a ride smoother than Downtown Montreal at sunrise. First-class travel.", dailyRate: 999, weekendRate: 1099, weeklyRate: 999, securityDeposit: 1590, horsepower: 550, engine: "4.0L V8 Biturbo", zeroToSixty: "4.8s", topSpeed: "130 mph", transmission: "Automatic", drivetrain: "AWD", seats: 5, doors: 4, luggage: 5, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 9, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368636520-674g0y.jpeg", alt: "Mercedes-Maybach GLS 600", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368638808-5u1w2c.jpeg", alt: "Mercedes-Maybach GLS 600", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "10", slug: "porsche-911-4s-techart", make: "Porsche", model: "911 4S TECHART", year: 2024, category: "PERFORMANCE", bodyStyle: "COUPE", tagline: "The icon, reimagined.", description: "TechArt aero, flat-six turbo screaming. Pure driving, zero compromise. The 911 perfected.", dailyRate: 999, weekendRate: 1099, weeklyRate: 999, securityDeposit: 1590, horsepower: 443, engine: "3.0L Flat-6 Biturbo", zeroToSixty: "3.2s", topSpeed: "190 mph", transmission: "PDK", drivetrain: "AWD", seats: 4, doors: 2, luggage: 2, convertible: false, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 10, images: [{ url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368953926-op8bi5.jpeg", alt: "Porsche 911 4S TECHART", isMain: true }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368910188-dokzpj.jpeg", alt: "Porsche 911 4S TECHART", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368907398-bxdkfj.jpeg", alt: "Porsche 911 4S TECHART", isMain: false }, { url: "https://tnkb8phzp3j6euwn.public.blob.vercel-storage.com/vehicles/1785368830415-lqz2nl.jpeg", alt: "Porsche 911 4S TECHART", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "11", slug: "audi-r8-spyder", make: "Audi", model: "R8 Spyder", year: 2024, category: "EXOTIC", bodyStyle: "CONVERTIBLE", tagline: "Mid-engine V10 symphony.", description: "Drop the top on Sainte-Catherine and let the sound do the talking. The everyday supercar with a soundtrack.", dailyRate: 1299, weekendRate: 1399, weeklyRate: 1299, securityDeposit: 1390, horsepower: 602, engine: "5.2L V10", zeroToSixty: "3.5s", topSpeed: "204 mph", transmission: "Dual-Clutch", drivetrain: "AWD", seats: 2, doors: 2, luggage: 1, convertible: true, available: true, featured: true, premierVerified: true, instantConfirm: true, displayOrder: 11, images: [{ url: "https://www.jswluxurygroup.com/cars/audi-r8-spyder/web/24p06368.jpg", alt: "Audi R8 Spyder", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/audi-r8-spyder/web/24p06442.jpg", alt: "Audi R8 Spyder", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/audi-r8-spyder/web/24p06397.jpg", alt: "Audi R8 Spyder", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/audi-r8-spyder/web/24p06378.jpg", alt: "Audi R8 Spyder", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "13", slug: "bmw-m4-competition-kith", make: "BMW", model: "M4 Competition x KITH", year: 2024, category: "PERFORMANCE", bodyStyle: "COUPE", tagline: "The KITH collab turns an M4 into a statement.", description: "Limited edition presence. The KITH collaboration adds exclusive styling to an already aggressive M4.", dailyRate: 599, weekendRate: 699, weeklyRate: 599, securityDeposit: 1150, horsepower: 503, engine: "3.0L I6 Biturbo", zeroToSixty: "3.8s", topSpeed: "180 mph", transmission: "Automatic", drivetrain: "RWD", seats: 4, doors: 2, luggage: 2, convertible: false, available: true, featured: false, premierVerified: true, instantConfirm: true, displayOrder: 13, images: [{ url: "https://www.jswluxurygroup.com/cars/bmw-m4-kith/web/m4-kith-1.jpg", alt: "BMW M4 Competition x KITH", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/bmw-m4-kith/web/m4-kith-4.jpg", alt: "BMW M4 Competition x KITH", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/bmw-m4-kith/web/m4-kith-7.jpg", alt: "BMW M4 Competition x KITH", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/bmw-m4-kith/web/m4-kith-10.jpg", alt: "BMW M4 Competition x KITH", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "14", slug: "bentley-bentayga", make: "Bentley", model: "Bentayga", year: 2024, category: "LUXURY", bodyStyle: "SUV", tagline: "British luxury meets SUV capability.", description: "The Bentayga glides over Montreal like nothing else on the road. Handcrafted luxury with go-anywhere ability.", dailyRate: 699, weekendRate: 799, weeklyRate: 699, securityDeposit: 990, horsepower: 542, engine: "4.0L V8 Biturbo", zeroToSixty: "4.4s", topSpeed: "180 mph", transmission: "Automatic", drivetrain: "AWD", seats: 5, doors: 4, luggage: 5, convertible: false, available: true, featured: false, premierVerified: true, instantConfirm: true, displayOrder: 14, images: [{ url: "https://www.jswluxurygroup.com/cars/bentley-bentayga/web/24p06605.jpg", alt: "Bentley Bentayga", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/bentley-bentayga/web/24p06573.jpg", alt: "Bentley Bentayga", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "15", slug: "range-rover-sport-svr", make: "Range Rover", model: "Sport SVR", year: 2024, category: "LUXURY", bodyStyle: "SUV", tagline: "British luxury meets supercar pace.", description: "The SVR dominates Old Montreal and glides through the Old Port. Supercharged V8 with Range Rover refinement.", dailyRate: 899, weekendRate: 999, weeklyRate: 899, securityDeposit: 990, horsepower: 575, engine: "5.0L V8 Supercharged", zeroToSixty: "4.3s", topSpeed: "176 mph", transmission: "Automatic", drivetrain: "AWD", seats: 5, doors: 4, luggage: 4, convertible: false, available: true, featured: false, premierVerified: true, instantConfirm: true, displayOrder: 15, images: [{ url: "https://www.jswluxurygroup.com/cars/range-rover-svr/web/24p05367.jpg", alt: "Range Rover Sport SVR", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/range-rover-svr/web/24p05350.jpg", alt: "Range Rover Sport SVR", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/range-rover-svr/web/24p05359.jpg", alt: "Range Rover Sport SVR", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "16", slug: "bmw-m4-competition", make: "BMW", model: "M4 Competition", year: 2024, category: "PERFORMANCE", bodyStyle: "CONVERTIBLE", tagline: "Top down, turbos spooled.", description: "The M4 Comp is Downtown Montreal with the volume turned all the way up. Twin-turbo inline-six with a folding hardtop.", dailyRate: 599, weekendRate: 699, weeklyRate: 599, securityDeposit: 790, horsepower: 503, engine: "3.0L I6 Biturbo", zeroToSixty: "3.6s", topSpeed: "180 mph", transmission: "Automatic", drivetrain: "RWD", seats: 4, doors: 2, luggage: 2, convertible: true, available: true, featured: false, premierVerified: true, instantConfirm: true, displayOrder: 16, images: [{ url: "https://www.jswluxurygroup.com/cars/bmw-m4-competition/web/24p06651-2.jpg", alt: "BMW M4 Competition", isMain: true, position: "50% 68%" }, { url: "https://www.jswluxurygroup.com/cars/bmw-m4-competition/web/24p06612.jpg", alt: "BMW M4 Competition", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/bmw-m4-competition/web/24p06632.jpg", alt: "BMW M4 Competition", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "17", slug: "mercedes-amg-c63-cabriolet", make: "Mercedes-AMG", model: "C63 Cabriolet", year: 2024, category: "PERFORMANCE", bodyStyle: "CONVERTIBLE", tagline: "AMG twin-turbo V8 in a four-seat convertible.", description: "The perfect blend of refinement and raw power. Handcrafted AMG engine with open-air freedom.", dailyRate: 599, weekendRate: 699, weeklyRate: 599, securityDeposit: 790, horsepower: 503, engine: "4.0L V8 Biturbo", zeroToSixty: "4.0s", topSpeed: "174 mph", transmission: "Automatic", drivetrain: "RWD", seats: 4, doors: 2, luggage: 2, convertible: true, available: true, featured: false, premierVerified: true, instantConfirm: true, displayOrder: 17, images: [{ url: "https://www.jswluxurygroup.com/cars/mercedes-c63/web/24p06518.jpg", alt: "Mercedes-AMG C63 Cabriolet", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/mercedes-c63/web/24p06488.jpg", alt: "Mercedes-AMG C63 Cabriolet", isMain: false }, { url: "https://www.jswluxurygroup.com/cars/mercedes-c63/web/24p06498.jpg", alt: "Mercedes-AMG C63 Cabriolet", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
  { id: "18", slug: "cadillac-escalade", make: "Cadillac", model: "Escalade", year: 2024, category: "LUXURY", bodyStyle: "SUV", tagline: "The icon of Montreal streets.", description: "Rolling in an Escalade is a statement before you even step out. American luxury with undeniable presence.", dailyRate: 599, weekendRate: 599, weeklyRate: 599, securityDeposit: 700, horsepower: 420, engine: "6.2L V8", zeroToSixty: "5.8s", topSpeed: "130 mph", transmission: "Automatic", drivetrain: "AWD", seats: 7, doors: 4, luggage: 6, convertible: false, available: true, featured: false, premierVerified: true, instantConfirm: true, displayOrder: 18, images: [{ url: "https://www.jswluxurygroup.com/cars/cadillac-escalade/web/24p06735.jpg", alt: "Cadillac Escalade", isMain: true }, { url: "https://www.jswluxurygroup.com/cars/cadillac-escalade/web/24p06783.jpg", alt: "Cadillac Escalade", isMain: false }], badges: [{ name: "verified", label: "Verified", icon: "shield-check" }] },
];

export const faqs = [
  { id: "faq-1", question: "What is the minimum age to rent?", answer: "The minimum age to rent most vehicles is 25. Select vehicles may be available to drivers 21+ with additional requirements.", sortOrder: 1 },
  { id: "faq-2", question: "Is a security deposit required?", answer: "Yes, a refundable security deposit is required for all rentals. The amount varies by vehicle and is fully refundable upon safe return.", sortOrder: 2 },
  { id: "faq-3", question: "What documents are required?", answer: "A valid driver's license, proof of insurance, and a major credit card in the renter's name are required.", sortOrder: 3 },
  { id: "faq-4", question: "Is insurance required?", answer: "Yes, valid insurance coverage is required. We can also arrange coverage through our partners if needed.", sortOrder: 4 },
  { id: "faq-5", question: "Is delivery available?", answer: "By default, vehicles are picked up at our Montreal location, detailed and fueled. Delivery is available by special arrangement within Montreal-Dade and Laval County—contact our concierge to coordinate.", sortOrder: 5 },
  { id: "faq-6", question: "Can vehicles be delivered to an airport or hotel?", answer: "Delivery to airports, hotels, residences, and marinas is available by special arrangement and quoted on request. Most customers pick up at our Montreal location for the fastest turnaround.", sortOrder: 6 },
  { id: "faq-7", question: "How much mileage is included?", answer: "Most rentals include 100 miles per day. Additional mileage is available at a per-mile rate.", sortOrder: 7 },
  { id: "faq-8", question: "Can additional drivers be added?", answer: "Yes, additional drivers can be added for a fee. All drivers must meet the same age and documentation requirements.", sortOrder: 8 },
  { id: "faq-9", question: "What is the cancellation policy?", answer: "Full refund with 72+ hours notice. 50% refund with 24-72 hours notice. No refund within 24 hours.", sortOrder: 9 },
  { id: "faq-10", question: "Are same-day reservations available?", answer: "Yes, subject to availability. Contact our concierge team for same-day requests.", sortOrder: 10 },
  { id: "faq-11", question: "How does the verification process work?", answer: "We verify your identity, driving record, and insurance. The process typically takes under 30 minutes.", sortOrder: 11 },
  { id: "faq-12", question: "Are prices displayed with taxes and fees?", answer: "Displayed prices are before taxes and fees. Final pricing is confirmed before reservation.", sortOrder: 12 },
  { id: "faq-13", question: "Can I request a vehicle not currently listed?", answer: "Yes, our concierge team can source specific vehicles through our partner network.", sortOrder: 13 },
];

export const reviews = [
  { id: "rev-1", rating: 5, title: "Exceptional service", text: "Picked up the Huracán at their Montreal location. Impeccable condition, full tank, and the concierge walked me through everything. Will definitely rent again.", customerLabel: "Montreal Beach", verified: true, rentalDate: "June 2026", vehicle: "Lamborghini Huracán EVO" },
  { id: "rev-2", rating: 5, title: "Worth every penny", text: "Rented the G63 for a weekend in Laurentians. The Urban Kit turns heads everywhere. Pickup was seamless and the car was spotless.", customerLabel: "Old Montreal", verified: true, rentalDate: "June 2026", vehicle: "Mercedes-AMG G63" },
  { id: "rev-3", rating: 5, title: "Best rental experience in Montreal", text: "I've rented from every exotic car company in Montreal. Premier is on another level. The Maybach was flawless and the service was white-glove.", customerLabel: "Westmount", verified: true, rentalDate: "May 2026", vehicle: "Mercedes-Maybach S680" },
  { id: "rev-4", rating: 5, title: "Made our wedding perfect", text: "Rented the Bentley Bentayga for our wedding day. Arrived early, detailed to perfection, and the driver was professional. Made our day unforgettable.", customerLabel: "Plateau Mont-Royal", verified: true, rentalDate: "May 2026", vehicle: "Bentley Bentayga" },
  { id: "rev-5", rating: 4, title: "Great experience overall", text: "The 911 was incredible to drive. Only minor issue was a slight delay at pickup, but the concierge kept me updated throughout.", customerLabel: "Downtown Montreal", verified: true, rentalDate: "April 2026", vehicle: "Porsche 911 4S" },
  { id: "rev-6", rating: 5, title: "The Urus is a beast", text: "Rented the Performante for a photoshoot. Client was blown away. Arranged delivery to the studio and the car was spotless.", customerLabel: " Griffintown", verified: true, rentalDate: "April 2026", vehicle: "Lamborghini Urus Performante" },
];
